Final project
Leeoasis/fortune500-companies pull request #3
Opened 2023-04-20 17:22 UTC by Leeoasis

Completed tasks in this pull request🌳 

- [ ] https://www.loom.com/share/b41d3faaa6fd4ce984e4d1bd6d337edd
- [ ] Use store, actions, and reducers in React.
- [ ] Connect React and Redux.
- [ ] Connect an existing API via Redux and use the display the data in the UI.
- [ ] write tests.

2023-04-20 18:28 UTC, christianbiring1 requested changes
Hi @Leeoasis , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
# REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/233455227-cd47679b-1367-4ab4-8b9f-f7e5de2eacfa.gif)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-20 18:28 UTC, christianbiring1 commented on README.md
> +I would like to thank [Microverse](https://www.microverse.org/), for the original [design guidelines](<https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)>)
- [ ] Instead of microverse, kindly make sure you acknowledge rather Nelson Sakwa the designer of the app.

2023-04-20 18:28 UTC, christianbiring1 commented on src/components/Navbar.js
> +
- [ ] As it is the case on the original design, Kinldy make sure you have the navigation bar set on your home page as is the case on the original design.
### Original design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/233449487-65ef116b-0456-484e-b913-0e3d4f00b8a6.png)

### Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/233449639-d3804e78-f6fe-4b04-a67f-7294575d8682.png)

2023-04-20 18:28 UTC, christianbiring1 commented on src/components/details.js
> +            <div className="company-name">
- [ ] Kindly you might consider sticking to the original design, as much as possible. the structure, spacing, and ... must look similar. Kindly adjust your details page to look similar to the template.
as you may see, we have a structure like:
- A navbar on the top
- Name of the company 
- The details about the company
### Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/233450931-f181d3cc-7af4-434c-b37d-891197d4e753.png)
### Original template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/233451123-8ad8f105-7d2e-4792-b040-ebd1498adee8.png)

2023-04-20 18:28 UTC, christianbiring1 commented on src/components/details.js
> +        console.error(error);
[OPTIONAL]
- [ ] You may also consider adhering to the code best practice by deleting all the `console.log` in your codebase.

2023-04-21 09:18 UTC, DuaneDave approved these changes
Hi @Leeoasis 👋, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-04-21 09:28 UTC, merged